replacements:
    world:
        DIRT:
            HAND:
                time: 1
                actions: [destroy]
            DIAMOND_SHOVEL:
                time: 20
                actions: [destroy, drop]
