name: ${project.name}
version: ${project.version}
description:  ${project.description}
author: totokaka
website: ${project.url}
dev-url: ${project.url}

main: me.totokaka.specifictools.SpecificTools
database: false

commands:
  SpecificTools:
    aliases: [Tools, st]
    description: List, create, edit or delete replacements
    permission: SpecificTools.command.specifictools
    usage: |
      /<command> [edit|create|delete|list] (Block)
      Example: /<command> list
      Example: /<command> create Dirt
      Example: /<command> edit Dirt
      Example: /<command> delete Dirt
  SpecificToolsAdd:
    aliases: [toolsAdd, sAdd, tAdd]
    description: Add a tool to a replacement
    permission: SpecificTools.command.specifictoolsadd
    usage: |
      /<command> [tool]
      Example: /<command> Diamond_sword
  SpecificToolsRemove:
    aliases: [toolsRemove, sRemove, tRemove]
    description: Remove a tool from a replacement
    permission: SpecificTools.command.specifictoolsremove
    usage: |
      /<command> [tool]
      Example: /<command> Diamond_sword

permissions:
  SpecificTools.*:
    description: Gives access to all SpecificTools commands
    default: op
    children:
      SpecificTools.defaults: false
      SpecificTools.replacements.*: true
      
  SpecificTools.defaults:
    description: Makes only the default tools valid for the player
    default: false
    
  SpecificTools.replacements.*:
    description: Makes the player able to create, delete, edit and list replacements.
    children:
      SpecificTools.replacements.create: true
      SpecificTools.replacements.delete: true
      SpecificTools.replacements.edit: true
      SpecificTools.replacements.list: true
  SpecificTools.replacements.create:
    description: Makes the player able to create replacements
    children:
      SpecificTools.command.specifictools: true
      SpecificTools.command.specifictoolsadd: true
  SpecificTools.replacements.delete:
    description: Makes the player able to delete replacements
    children:
      SpecificTools.command.specifictools: true
  SpecificTools.replacements.edit:
    description: Makes the player able to edit replacements
    children:
      SpecificTools.command.specifictools: true
      SpecificTools.command.specifictoolsadd: true
      SpecificTools.command.specifictoolsremove: true
  SpecificTools.replacements.list:
    description: Makes the player able to list all the replacements
    children:
      SpecificTools.command.specifictools: true