name: ${project.name}
version: ${project.version}
description:  ${project.description}
author: totokaka
website: ${project.url}
dev-url: ${project.url}

main: me.totokaka.specifictools.SpecificTools
database: false

permissions:
  SpecificTools.*:
    description: Gives access to all SpecificTools commands
    children:
      SpecificTools.defaults: true
  SpecificTools.defaults:
    description: Does so you need to use the default tools.
    default: false